require File.expand_path('../config/application', __FILE__)
require 'rake/testtask'

Rails.application.load_tasks
Rake::TestTask.new(:test) do |test|
  test.pattern = 'test/**/test_*.rb'
end

task :default => :test
