source 'https://rubygems.org'

# This is the default Gemfile generated
# by Rails4, streamlined for testing
# frontkiq

gem 'rails', '4.2.3'

gem 'sass-rails', '~> 5.0'

gem 'jquery-rails'
gem 'turbolinks'

# frontkiq setup
gem 'sidekiq'
gem 'frontkiq', path: '../'

group :development, :test do
  gem 'byebug'
  gem 'minitest'
end

